### ISSUE TITLE
SATA HDD not detected

### ISSUE THREAD

**Issue by t-abraham** [Virusmater/OdroidXU4-Cloudshell2-OMV#1]
Hi,
I followed every steps you wrote in the readme file. I am getting the Fan running as well as the LCD but the 2 SATA HDD are not detected in the OVM. Can you please help me out?

**Comment by Virusmater** [comment]
Some more info? Did you put Cloudshell 2 dip switches to the right position? Do you hear them starting spinning? Do you have /dev/sd* devices? Can you see em in the linux console?
Also check and clean your USB3 connection ports on XU4

**Comment by ghostkernel-core** [comment]
Hi, the problem got solved. It was the cable, I believe one or more wires broke off due to the twistings... a simple replacement of the USB cable solved everything.
